#!/bin/bash

case $2 in
  "api" )
    pensieve -s ${1}-${2} -i felipellrocha/node
  ;;
  "banking"|"recommender"|"analysis"|"bridge"|"housing"|"auth"|"budget"|"iex"|"market"|"plaid"|"trader"|"user")
    pensieve -s ${1}-${2} -i felipellrocha/rust:latest
  ;;
  * )
    echo "Method not found. Good bye!"
  ;;
esac
