#!/bin/bash


function watch-log() {
  location=$(git rev-parse --show-toplevel)
  fswatch -or $location/.git -e $location/.git/index.lock | while read MODFILE
  do
    tty=$(ps -o tty= -p $$)
    pids=$(pgrep -t $tty $PAGER)
    while read -r pid; do
      echo $pid
      kill -9 $pid
    done <<< "$pids"
 done
}

function logger() {
  clear;
  git --paginate log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset)%C(bold yellow)%d%C(reset) %C(white)%s%C(reset) - %C(bold green)(%ar)%C(reset)' --all
}

function watch-diff-cached() {
  location=$(git rev-parse --show-toplevel)
  fswatch -o $location/.git/index $location/.git/logs/HEAD | while read MODFILE
  do
    tty=$(ps -o tty= -p $$)
    pids=$(pgrep -t $tty $PAGER)
    while read -r pid; do
      echo $pid
      kill -9 $pid
    done <<< "$pids"
  done
}

function cacher() {
  clear;
  git --paginate diff --cached
}

function watch-diff() {
  location=$(git rev-parse --show-toplevel)
  fswatch -or $location -e "*($location/.git/index.lock|node_modules|dist)*" | while read MODFILE
  do
    tty=$(ps -o tty= -p $$)
    pids=$(pgrep -t $tty $PAGER)
    while read -r pid; do
      echo $pid
      kill -9 $pid
    done <<< "$pids"
  done
}

function differ() {
  clear;
  git --paginate diff
}

function watch-status() {
  location=$(git rev-parse --show-toplevel)
  echo $location
  fswatch -o $location/.git/index $location/.git/logs/HEAD | while read MODFILE
  do
    tty=$(ps -o tty= -p $$)
    pids=$(pgrep -t $tty $PAGER)
    while read -r pid; do
      echo $pid
      kill -9 $pid
    done <<< "$pids"
  done
}

function get-status {
  clear;
  git --paginate status
}

case $1 in
  "log" )
    watch-log &
    while true; do
      logger
    done
  ;;
  "cache" )
    watch-diff-cached &
    while true; do
      cacher
    done
  ;;
  "diff" )
    watch-diff &
    while true; do
      differ
    done
  ;;
  "status" )
    watch-status &
    while true; do
      get-status
    done
  ;;
  * )
    echo "Watcher not found. Good bye!"
  ;;
esac
